name: "godot-ci export"
on:
  push:
    tags:
      - v*

env:
  GODOT_VERSION: 4.1.3
  EXPORT_NAME: SLAIME
  PROJECT_PATH: "."

jobs:
  export-windows:
    name: Windows Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.1.3
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Windows Build
        run: |
          mkdir -v -p build/windows
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "Windows Desktop" ./build/windows/$EXPORT_NAME-${{github.ref}}.exe
      - name: Upload Artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: windows
          path: build/windows/${{ env.EXPORT_NAME }}-${{github.ref}}.exe
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/windows/${{ env.EXPORT_NAME }}-${{github.ref}}.exe

  # export-linux:
  #   name: Linux Export
  #   runs-on: ubuntu-20.04
  #   container:
  #     image: barichello/godot-ci:4.1.3
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4.1.2
  #       with:
  #         lfs: true
  #     - name: Setup
  #       run: |
  #         mkdir -v -p ~/.local/share/godot/export_templates/
  #         mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
  #     - name: Linux Build
  #       run: |
  #         mkdir -v -p build/linux
  #         cd $PROJECT_PATH
  #         godot --headless --verbose --export-release "Linux/X11" ./build/linux/$EXPORT_NAME.linux.bin
  #     - name: Upload Artifact
  #       uses: actions/upload-artifact@v4.3.1
  #       with:
  #         name: linux
  #         path: build/linux/${{ env.EXPORT_NAME }}.linux.bin
  #     - name: Release
  #       uses: softprops/action-gh-release@v2
  #       if: startsWith(github.ref, 'refs/tags/')
  #       with:
  #         files: |
  #           build/linux/${{ env.EXPORT_NAME }}.linux.bin

  # export-web:
  #   name: Web Export
  #   runs-on: ubuntu-20.04
  #   container:
  #     image: barichello/godot-ci:4.1.3
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4.1.2
  #       with:
  #         lfs: true
  #     - name: Setup
  #       run: |
  #         mkdir -v -p ~/.local/share/godot/export_templates/
  #         mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
  #     - name: Web Build
  #       run: |
  #         mkdir -v -p build/web
  #         cd $PROJECT_PATH
  #         godot --headless --verbose --export-release "HTML5" ./build/web/index.html
  #         cd build/web/ && zip ../$EXPORT_NAME.web.zip ./* && cd $PROJECT_PATH
  #     - name: Upload Artifact
  #       uses: actions/upload-artifact@v4.3.1
  #       with:
  #         name: web
  #         path: build/web/
  #     - name: Release
  #       uses: softprops/action-gh-release@v2
  #       if: startsWith(github.ref, 'refs/tags/')
  #       with:
  #         files: |
  #           build/${{ env.EXPORT_NAME }}.web.zip
  #     # - name: Install rsync ðŸ“š
  #     #   run: |
  #     #     apt-get update && apt-get install -y rsync
  #     # - name: Deploy to GitHub Pages ðŸš€
  #     #   uses: JamesIves/github-pages-deploy-action@releases/v4
  #     #   with:
  #     #     branch: gh-pages # The branch the action should deploy to.
  #     #     folder: build/web # The folder the action should deploy.

  # export-mac:
  #   name: Mac Export
  #   runs-on: ubuntu-20.04
  #   container:
  #     image: barichello/godot-ci:4.1.3
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4.1.2
  #       with:
  #         lfs: true
  #     - name: Setup
  #       run: |
  #         mkdir -v -p ~/.local/share/godot/export_templates/
  #         mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
  #     - name: Mac Build
  #       run: |
  #         mkdir -v -p build/mac
  #         cd $PROJECT_PATH
  #         godot --headless --verbose --export-release "macOS" ./build/mac/$EXPORT_NAME.macos.zip
  #     - name: Upload Artifact
  #       uses: actions/upload-artifact@v4.3.1
  #       with:
  #         name: mac
  #         path: build/mac/${{ env.EXPORT_NAME }}.macos.zip
  #     - name: Release
  #       uses: softprops/action-gh-release@v2
  #       if: startsWith(github.ref, 'refs/tags/')
  #       with:
  #         files: |
  #           build/mac/${{ env.EXPORT_NAME }}.macos.zip
